### PR TITLE
Github -> GitHub

### PR DESCRIPTION
**Pull request by Coccocoahelper**
Very simple, not ready yet

### CODE REVIEW

**Comment by Coccocoahelper** [comment]
Ready to merge.

**Comment by lkhrs** [comment]
Merging because I can’t unsee it now.

**Comment by kevquirk** [comment]
It must have been me who wrote that, but I know it's "GitHub" so I have no idea how I managed to end up writing "Github" like, THREE TIMES!

Thanks for the PR.

**Comment by Coccocoahelper** [comment]
> It must have been me who wrote that, but I know it's "GitHub" so I have no idea how I managed to end up writing "Github" like, THREE TIMES!
> 
> Thanks for the PR.

You're welcome!

**Pull request merged**
